[project]
name = "spectro"
version = "2.0.0"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
    "soundfile",
    "pillow"
]

[project.scripts]
spectro = "spectro.cli:main"

[tool.setuptools]
packages = ["spectro", "spectro.commands"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
